// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-fCWhlbWEoSHYa9DOx2jDYr9azp5h14M',
    appId: '1:525996237230:web:575334d2aa801b703fe83f',
    messagingSenderId: '525996237230',
    projectId: 'courseproject-3c717',
    authDomain: 'courseproject-3c717.firebaseapp.com',
    storageBucket: 'courseproject-3c717.firebasestorage.app',
    measurementId: 'G-QPMZSEEM6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIMx7JUnQc-JKp9RUlBPpfDtSNEl0G9U',
    appId: '1:525996237230:android:578149c14d1241533fe83f',
    messagingSenderId: '525996237230',
    projectId: 'courseproject-3c717',
    storageBucket: 'courseproject-3c717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqIDSPzazaPvCgyk50by6l2CGQh7m8ZU',
    appId: '1:525996237230:ios:561d68587259a4453fe83f',
    messagingSenderId: '525996237230',
    projectId: 'courseproject-3c717',
    storageBucket: 'courseproject-3c717.firebasestorage.app',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqIDSPzazaPvCgyk50by6l2CGQh7m8ZU',
    appId: '1:525996237230:ios:561d68587259a4453fe83f',
    messagingSenderId: '525996237230',
    projectId: 'courseproject-3c717',
    storageBucket: 'courseproject-3c717.firebasestorage.app',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-fCWhlbWEoSHYa9DOx2jDYr9azp5h14M',
    appId: '1:525996237230:web:a8261fa7089c5e0e3fe83f',
    messagingSenderId: '525996237230',
    projectId: 'courseproject-3c717',
    authDomain: 'courseproject-3c717.firebaseapp.com',
    storageBucket: 'courseproject-3c717.firebasestorage.app',
    measurementId: 'G-93H3KE75T4',
  );
}
